name: Force Labels
description: Will check for labels attached to the PR and fail if one of the labels in the list are missing.
branding:
  icon: 'tag'
  color: 'gray-dark'

on:
  pull_request:
    branches: 
    - development
    types: [ labeled, opened, unlabeled ]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Labels added
      if: ${{ contains(fromJson('["bug", "documentation", "enhancement"]'), github.event.label.name) == true }}
      run: echo Pass
    - name: Labels not added (bug, documentation, or enhancement)
      if: ${{ contains(fromJson('["bug"]'), github.event.label.name) != true }}
      run: exit 1
      
